extension to backport the PractitionerRole.characteristic element for R4
NHSDigital/NHSEngland-FHIR-Programme-ImplementationGuide pull request #118
Opened 2024-12-16 15:39 UTC by vickyjaiswal0308

2024-12-16 15:47 UTC, ryma2fhir approved these changes

2024-12-17 08:51 UTC, ryma2fhir requested changes

2024-12-17 10:43 UTC, NaminderSoorma approved these changes
The Extension looks OK to replicate R5 

(https://hl7.org/fhir/R5/practitionerrole-definitions.html#PractitionerRole.characteristic)

2024-12-17 11:08 UTC, vickyjaiswal0308 commented on structuredefinitions/Extension-England-PractitionerRole-Characteristic.xml
> +  <url value="http://hl7.org/fhir/R5/StructureDefinition/extension-PractitionerRole.characteristic" />
changed it to 5.0

2024-12-17 11:47 UTC, ryma2fhir requested changes
Suggest creating the extension in Forge to undestand what should and should not go into the differential. Using Forge also gives another layer of validation and should be used whenever possible.

2024-12-17 11:47 UTC, ryma2fhir commented on structuredefinitions/Extension-England-PractitionerRole-Characteristic.xml
> +      <max value="*" />
This is a differential so I don't understand why min and max are in when they haven't been changed? I guess you didn't use Forge?

2024-12-17 11:47 UTC, ryma2fhir commented on structuredefinitions/Extension-England-PractitionerRole-Characteristic.xml
> +      <mustSupport value="false" />
Not needed

2024-12-17 11:47 UTC, ryma2fhir commented on structuredefinitions/Extension-England-PractitionerRole-Characteristic.xml
> +      <max value="1" />
not needed as this is default

2024-12-17 11:47 UTC, ryma2fhir commented on structuredefinitions/Extension-England-PractitionerRole-Characteristic.xml
> +      <min value="0" />
not needed as this is default

2024-12-17 12:51 UTC, vickyjaiswal0308 commented
> @vickyjaiswal0308 Suggest creating the extension in Forge to understand what should and should not go into the differential. Using Forge also gives another layer of validation and should be used whenever possible.

@ryma2fhir , I haven't used forge because i think for an external user who don't have much knowledge of FHIR , It's a good practice  to communicate FHIR cardinalities and constraints to external users in a simple, visible, or instructional format, avoiding Forge and directly documenting the cardinalities. Not all external users will be familiar with Forge outputs or its technical representations. This aligns with the idea of creating a more user-focused deliverable rather than relying solely on Forge outputs, which can sometimes be overly technical or abstract. But , I understand your concern related to validation. I will create it through forge now.

2024-12-17 13:11 UTC, ryma2fhir commented
> > @vickyjaiswal0308 Suggest creating the extension in Forge to understand what should and should not go into the differential. Using Forge also gives another layer of validation and should be used whenever possible.
> 
> @ryma2fhir , I haven't used forge because i think for an external user who don't have much knowledge of FHIR , It's a good practice to communicate FHIR cardinalities and constraints to external users in a simple, visible, or instructional format, avoiding Forge and directly documenting the cardinalities. Not all external users will be familiar with Forge outputs or its technical representations. This aligns with the idea of creating a more user-focused deliverable rather than relying solely on Forge outputs, which can sometimes be overly technical or abstract. But , I understand your concern related to validation. I will create it through forge now.

The best practice is to have a standardised approach, the element `differential` and `snapshot` are clearly defined in base FHIR. What you are doing is something in-between. If you disagree with this, and the use of Forge it is best to bring it up in the team meeting.
https://build.fhir.org/structuredefinition-definitions.html#StructureDefinition.differential

2024-12-17 13:49 UTC, ryma2fhir approved these changes

2024-12-17 14:10 UTC, merged