Patient flag ig
NHSDigital/NHSEngland-FHIR-Programme-ImplementationGuide pull request #58
Opened 2024-06-03 10:27 UTC by vickyjaiswal0308

Added Examples for Patient Flag IG

2024-06-03 12:47 UTC, ryma2fhir requested changes

2024-06-03 12:47 UTC, ryma2fhir commented on examples/AddCPISRecordTransaction-Bundle-Example.xml
> +                           value="https://sds.spineservices.nhs.uk/STU3/Practitioner/2ee4tr6a9" />
We shouldn't be referencing STU3 as it is incompatible with R4.

2024-06-10 14:00 UTC, marcusfearnett-nhsdigital commented on examples/AddCPISRecordTransaction-Bundle-Example.xml
> +                           value="https://sds.spineservices.nhs.uk/STU3/Practitioner/2ee4tr6a9" />
Agree for the references. Just go to value="https://sds.spineservices.nhs.uk/Practitioner/2ee4tr6a9" etc.
Unfortunately, we'll have to leave all the codesystem STU3s as tey're not refs, but canonicals.

2024-06-10 14:02 UTC, marcusfearnett-nhsdigital requested changes
Have reviewed. Changes suggested (or not).

Have set as 'Request changes' as above, and we need to think about taking out Consent

2024-06-10 14:25 UTC, ryma2fhir commented on examples/AddCPISRecordTransaction-Bundle-Example.xml
> +      <url value="Patient/UKCore-Patient-Example" />
My issue is that the UK Core does not have Patient/UKCore-Patient-Example

2024-06-12 18:14 UTC, vickyjaiswal0308 commented on examples/AddCPISRecordTransaction-Bundle-Example.xml
> +      <url value="Patient/UKCore-Patient-Example" />
I have change it to Patient/PatientFlag-AlanMann-Example in all the files.

2024-06-12 18:16 UTC, vickyjaiswal0308 commented on examples/AddCPISRecordTransaction-Bundle-Example.xml
> +                           value="https://sds.spineservices.nhs.uk/STU3/Practitioner/2ee4tr6a9" />
I have done the change and replace the value with "https://sds.spineservices.nhs.uk/Practitioner/2ee4tr6a9" and "https://directory.spineservices.nhs.uk/Organization/a3e5i7"

2024-06-13 11:59 UTC, ryma2fhir commented on examples/AddCPISRecordTransaction-Bundle-Example.xml
> +    <fullUrl value="Patient/PatientFlag-AlanMann-Example" />
This needs to be a full url, so something like "https://example.com/Patient/PatientFlag-AlanMann-Example"

2024-06-13 11:59 UTC, ryma2fhir commented on examples/AddCPISRecordTransaction-Bundle-Example.xml
> +                   value="https://fhir.nhs.uk/England/StructureDefinition/England-FlagCondition" />
We said that we'll change it to England-Flag-[RA?]-Condition. Shall we do this in another branch so not to confuse ourselves?

2024-06-13 11:59 UTC, ryma2fhir commented on examples/AddCPISRecordTransaction-Bundle-Example.xml
> +                          value="https://fhir.hl7.org.uk/STU3/CodeSystem/CareConnect-SDSJobRoleName-1" />
I'm not sure how this will work as it won't be in the package for validation. Probably one to discuss in the meeting today.

2024-06-13 11:59 UTC, ryma2fhir commented on examples/AddCPISRecordTransaction-Bundle-Example.xml
> +            <code value="CP-IS" />
we said the codes needs changing if we were the ones to create them, something like
<code>code value ="child-protection-information-sharing-flag"</code>
<code>display value="Child Protection - Information Sharing Flag"</code>

Again might be worth doing in a separate branch to avoid confusion

2024-06-13 11:59 UTC, ryma2fhir commented on examples/AddCPISRecordTransaction-Bundle-Example.xml
> +                   value="https://fhir.nhs.uk/England/StructureDefinition/England-PatientFlag" />
Can we pretty print as it should all be on one line

2024-06-13 11:59 UTC, ryma2fhir commented on examples/AddCPISRecordTransaction-Bundle-Example.xml
> +            <code value="001" />
code system needs changing, unless comes from somewhere like dm+d, then the codesystem url needs recording in the Codesystem

2024-06-13 12:47 UTC, vickyjaiswal0308 commented on examples/AddCPISRecordTransaction-Bundle-Example.xml
> +                   value="https://fhir.nhs.uk/England/StructureDefinition/England-FlagCondition" />
I have keep it as England-FlagCondition as these profiles should be generic as it will be used in CP-IS, FGM and RA Flags . As , we are working on Generic Patient Flag , it should not be particular to RA, FGM, etc.

2024-06-13 12:51 UTC, ryma2fhir commented on examples/AddCPISRecordTransaction-Bundle-Example.xml
> +                   value="https://fhir.nhs.uk/England/StructureDefinition/England-FlagCondition" />
then it should be Flag-Condition

2024-06-13 14:33 UTC, ryma2fhir approved these changes

2024-06-13 14:34 UTC, merged